import type { TFunction } from "i18next";
import {
  EFFICIENCY_ALERT_TYPE,
  PopulatedAlertSensorSchema,
  PopulatedBuildingSchema,
  type Alert,
} from "@wattguard/shared";

/**
 * Minimal structured fields used to compose a localized alert message.
 * The API stopped sending a pre-rendered `message` string; the frontend
 * composes it from these fields instead. Names come live from the populated
 * `building`/`sensor` relations.
 */
export type AlertMessageData = Pick<
  Alert,
  "type" | "building" | "sensor" | "value" | "unit" | "limit"
>;

/** Building display name, or a placeholder when unpopulated. */
export function getAlertBuildingName(alert: Pick<Alert, "building">): string {
  const parsed = PopulatedBuildingSchema.safeParse(alert.building);
  return parsed.success ? parsed.data.name : "—";
}

function getAlertSensor(alert: AlertMessageData) {
  if (!alert.sensor) return undefined;
  const parsed = PopulatedAlertSensorSchema.safeParse(alert.sensor);
  return parsed.success ? parsed.data : undefined;
}

/**
 * Compose a localized, human-readable message for an alert.
 *
 * Efficiency alerts (building-level, generated by the periodic evaluator) get
 * a dedicated message. When the structured threshold fields are present a
 * detailed "threshold exceeded" message is produced; otherwise a generic alert
 * message is used.
 */
export function composeAlertMessage(
  alert: AlertMessageData,
  t: TFunction,
): string {
  const buildingName = getAlertBuildingName(alert);
  const populatedSensor = getAlertSensor(alert);
  const sensorType = populatedSensor
    ? t(`sensors.type.${populatedSensor.sensorType}`, {
        defaultValue: populatedSensor.sensorType,
      })
    : buildingName;
  const location = populatedSensor?.location ?? buildingName;

  if (alert.type === EFFICIENCY_ALERT_TYPE) {
    return t("alerts.efficiencyBelowThreshold", {
      building: buildingName,
      value: alert.value != null ? Number(alert.value).toFixed(2) : "—",
      limit: alert.limit != null ? Number(alert.limit).toFixed(2) : "—",
    });
  }

  if (alert.value != null && alert.limit != null) {
    return t("alerts.thresholdExceeded", {
      sensorType,
      location,
      value: alert.value,
      unit: alert.unit ?? "",
      limit: alert.limit,
    });
  }

  return t("alerts.generic", { sensorType, location });
}

/** Localized label for an alert severity value. */
export function getAlertSeverityLabel(
  severity: string,
  t: TFunction,
): string {
  return t(`alerts.severity.${severity}`, { defaultValue: severity });
}

/** Localized label for an alert type value (falls back to the raw value). */
export function getAlertTypeLabel(type: string, t: TFunction): string {
  const key = `alerts.type.${type}`;
  const fallback = type.replace(/_/g, " ");
  return t(key, { defaultValue: fallback });
}
